/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as AboutSecurityRouteImport } from './routes/about-security'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransparencyRouteImport } from './routes/api/transparency'
import { Route as ApiSubmitSignatureRouteImport } from './routes/api/submit-signature'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiIssueSubmissionNonceRouteImport } from './routes/api/issueSubmissionNonce'
import { Route as ApiIssueNonceRouteImport } from './routes/api/issue-nonce'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHasAlreadySignedRouteImport } from './routes/api/has-already-signed'
import { Route as ApiFraudTransparencyRouteImport } from './routes/api/fraud-transparency'
import { Route as ApiSignaturesRecentRouteImport } from './routes/api/signatures.recent'
import { Route as ApiDebugLogsRouteImport } from './routes/api/debug/logs'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSecurityRoute = AboutSecurityRouteImport.update({
  id: '/about-security',
  path: '/about-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransparencyRoute = ApiTransparencyRouteImport.update({
  id: '/api/transparency',
  path: '/api/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitSignatureRoute = ApiSubmitSignatureRouteImport.update({
  id: '/api/submit-signature',
  path: '/api/submit-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssueSubmissionNonceRoute = ApiIssueSubmissionNonceRouteImport.update({
  id: '/api/issueSubmissionNonce',
  path: '/api/issueSubmissionNonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssueNonceRoute = ApiIssueNonceRouteImport.update({
  id: '/api/issue-nonce',
  path: '/api/issue-nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHasAlreadySignedRoute = ApiHasAlreadySignedRouteImport.update({
  id: '/api/has-already-signed',
  path: '/api/has-already-signed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFraudTransparencyRoute = ApiFraudTransparencyRouteImport.update({
  id: '/api/fraud-transparency',
  path: '/api/fraud-transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignaturesRecentRoute = ApiSignaturesRecentRouteImport.update({
  id: '/api/signatures/recent',
  path: '/api/signatures/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugLogsRoute = ApiDebugLogsRouteImport.update({
  id: '/api/debug/logs',
  path: '/api/debug/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-security': typeof AboutSecurityRoute
  '/stats': typeof StatsRoute
  '/api/fraud-transparency': typeof ApiFraudTransparencyRoute
  '/api/has-already-signed': typeof ApiHasAlreadySignedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/issue-nonce': typeof ApiIssueNonceRoute
  '/api/issueSubmissionNonce': typeof ApiIssueSubmissionNonceRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/submit-signature': typeof ApiSubmitSignatureRoute
  '/api/transparency': typeof ApiTransparencyRoute
  '/api/debug/logs': typeof ApiDebugLogsRoute
  '/api/signatures/recent': typeof ApiSignaturesRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-security': typeof AboutSecurityRoute
  '/stats': typeof StatsRoute
  '/api/fraud-transparency': typeof ApiFraudTransparencyRoute
  '/api/has-already-signed': typeof ApiHasAlreadySignedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/issue-nonce': typeof ApiIssueNonceRoute
  '/api/issueSubmissionNonce': typeof ApiIssueSubmissionNonceRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/submit-signature': typeof ApiSubmitSignatureRoute
  '/api/transparency': typeof ApiTransparencyRoute
  '/api/debug/logs': typeof ApiDebugLogsRoute
  '/api/signatures/recent': typeof ApiSignaturesRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-security': typeof AboutSecurityRoute
  '/stats': typeof StatsRoute
  '/api/fraud-transparency': typeof ApiFraudTransparencyRoute
  '/api/has-already-signed': typeof ApiHasAlreadySignedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/issue-nonce': typeof ApiIssueNonceRoute
  '/api/issueSubmissionNonce': typeof ApiIssueSubmissionNonceRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/submit-signature': typeof ApiSubmitSignatureRoute
  '/api/transparency': typeof ApiTransparencyRoute
  '/api/debug/logs': typeof ApiDebugLogsRoute
  '/api/signatures/recent': typeof ApiSignaturesRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-security'
    | '/stats'
    | '/api/fraud-transparency'
    | '/api/has-already-signed'
    | '/api/health'
    | '/api/issue-nonce'
    | '/api/issueSubmissionNonce'
    | '/api/ready'
    | '/api/stats'
    | '/api/submit-signature'
    | '/api/transparency'
    | '/api/debug/logs'
    | '/api/signatures/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-security'
    | '/stats'
    | '/api/fraud-transparency'
    | '/api/has-already-signed'
    | '/api/health'
    | '/api/issue-nonce'
    | '/api/issueSubmissionNonce'
    | '/api/ready'
    | '/api/stats'
    | '/api/submit-signature'
    | '/api/transparency'
    | '/api/debug/logs'
    | '/api/signatures/recent'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-security'
    | '/stats'
    | '/api/fraud-transparency'
    | '/api/has-already-signed'
    | '/api/health'
    | '/api/issue-nonce'
    | '/api/issueSubmissionNonce'
    | '/api/ready'
    | '/api/stats'
    | '/api/submit-signature'
    | '/api/transparency'
    | '/api/debug/logs'
    | '/api/signatures/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutSecurityRoute: typeof AboutSecurityRoute
  StatsRoute: typeof StatsRoute
  ApiFraudTransparencyRoute: typeof ApiFraudTransparencyRoute
  ApiHasAlreadySignedRoute: typeof ApiHasAlreadySignedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIssueNonceRoute: typeof ApiIssueNonceRoute
  ApiIssueSubmissionNonceRoute: typeof ApiIssueSubmissionNonceRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiSubmitSignatureRoute: typeof ApiSubmitSignatureRoute
  ApiTransparencyRoute: typeof ApiTransparencyRoute
  ApiDebugLogsRoute: typeof ApiDebugLogsRoute
  ApiSignaturesRecentRoute: typeof ApiSignaturesRecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-security': {
      id: '/about-security'
      path: '/about-security'
      fullPath: '/about-security'
      preLoaderRoute: typeof AboutSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transparency': {
      id: '/api/transparency'
      path: '/api/transparency'
      fullPath: '/api/transparency'
      preLoaderRoute: typeof ApiTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-signature': {
      id: '/api/submit-signature'
      path: '/api/submit-signature'
      fullPath: '/api/submit-signature'
      preLoaderRoute: typeof ApiSubmitSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issueSubmissionNonce': {
      id: '/api/issueSubmissionNonce'
      path: '/api/issueSubmissionNonce'
      fullPath: '/api/issueSubmissionNonce'
      preLoaderRoute: typeof ApiIssueSubmissionNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issue-nonce': {
      id: '/api/issue-nonce'
      path: '/api/issue-nonce'
      fullPath: '/api/issue-nonce'
      preLoaderRoute: typeof ApiIssueNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/has-already-signed': {
      id: '/api/has-already-signed'
      path: '/api/has-already-signed'
      fullPath: '/api/has-already-signed'
      preLoaderRoute: typeof ApiHasAlreadySignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fraud-transparency': {
      id: '/api/fraud-transparency'
      path: '/api/fraud-transparency'
      fullPath: '/api/fraud-transparency'
      preLoaderRoute: typeof ApiFraudTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signatures/recent': {
      id: '/api/signatures/recent'
      path: '/api/signatures/recent'
      fullPath: '/api/signatures/recent'
      preLoaderRoute: typeof ApiSignaturesRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/logs': {
      id: '/api/debug/logs'
      path: '/api/debug/logs'
      fullPath: '/api/debug/logs'
      preLoaderRoute: typeof ApiDebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutSecurityRoute: AboutSecurityRoute,
  StatsRoute: StatsRoute,
  ApiFraudTransparencyRoute: ApiFraudTransparencyRoute,
  ApiHasAlreadySignedRoute: ApiHasAlreadySignedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIssueNonceRoute: ApiIssueNonceRoute,
  ApiIssueSubmissionNonceRoute: ApiIssueSubmissionNonceRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiSubmitSignatureRoute: ApiSubmitSignatureRoute,
  ApiTransparencyRoute: ApiTransparencyRoute,
  ApiDebugLogsRoute: ApiDebugLogsRoute,
  ApiSignaturesRecentRoute: ApiSignaturesRecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
